#!/bin/bash

if [[ $(/usr/bin/id -u) -ne 0 ]]; then
        echo "Not running as root"
        exit
fi

DbFile=""

if [ -n "$1" ]; then
    if [[ $1 = "-t" ]]; then
               case $2 in
            #A record
            A )
                    echo 'Creating new '"$3"'record for ip '"$4"'& domain '"$5"''
                    echo -e "$3          IN      A       $4" >> /etc/bind/db."$5"
                    DbFile="/etc/bind/db.$5"
                    ;;

            # Cname record
                CNAME )
                echo 'Creating '"$3"'record with domain '"$4"''
                    DbFile="/etc/bind/db.$4"
                    echo -e ''"$3"'     IN      CNAME   '"$4"'.' >> "$DbFile"
                    ;;

	    # Mx record
                  MX )
                    echo 'Creating new '"$3"'record for ip'"$4"'& domain '"$5"''
                       echo -e "@      IN      MX      10      $3.$5." >> /etc/bind/db."$5"
                      echo -e "$3     IN      A       $4" >> /etc/bind/db."$5"
                       DbFile="/etc/bind/db.$5"
                        ;;
            esac
        else
               echo -e "$1     IN      A       $2" >> /etc/bind/db."$3"
             DbFile="/etc/bind/db.$3"
           fi

serial=$(grep "Serial" $DbFile)
    serialnumber=$(echo $serial |sed 's/[^0-9]*//g')
    ((serialnumber++))
    newserial="$serialnumber    ; Serial"
    echo $newserial;
    sed -i "s/$seriall/\t\t\t     $newserial/g" $DbFile
    echo -e 'update serial -> OK'

echo 'Restarting bind9'
    systemctl restart bind9
    echo "Done"
